Settings:
  prefix: "&f[ &e캐시 &f] "

  # [ ---------- 수표 기능 ---------- ]

  # 캐시 수표화 기능 사용 여부
  useCashCheck: false
  # 마일리지 수표화 기능 사용 여부
  useMileageCheck: false
  # 수표화 가능한 최소 금액
  minCashCheck: 100
  minMileageCheck: 100

  # 수표 아이템 커스터마이징
  # 플레이스 홀더 : <cash> <mileage>
  cashCheckItem:
    # 수표 아이템 타입  (변경전에 만들어진 수표는 변경후에도 사용 가능합니다.) 참고 : https://papermc.io/javadocs/paper/1.12/org/bukkit/Material.html
    ItemType: "PAPER"
    DisplayName: "&f[ &6수표 &f] &e<cash> 캐시"
    Lores:
      - "&f"
      - "&e우클릭 하여 <cash> 캐시를 획득합니다."

  mileageCheckItem:
    ItemType: "PAPER"
    DisplayName: "&f[ &6수표 &f] &e<mileage> 마일리지"
    Lores:
      - "&f"
      - "&e우클릭 하여 <mileage> 마일리지를 획득합니다."
